remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Life is better by bike
description: ... and here are the receipts
show_downloads:
google_analytics:
exclude:
  - docker-compose.yml
  - Gemfile