remote_theme: mmistakes/so-simple-theme
plugins:
- jekyll-remote-theme

title: Life is better by bike
description: ... here are the receipts
logo: "images/img/bike-logo-01.png"

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true

google_analytics:
include:
  - _pages
exclude:
  - docker-compose.yml
  - Gemfile

author:
  name: BikeSOMa_NJ
  picture:
  email:
  links:
    - title: Instagram
      url: https://instagram.com/bikesoma_nj
      icon: fab fa-instagram
    - title: Facebook
      url: https://www.facebook.com/profile.php?id=61560900343761
      icon: fab fa-facebook

footer_links:
  - title: Instagram
    url: https://instagram.com/bikesoma_nj
    icon: fab fa-instagram
  - title: Facebook
    url: https://www.facebook.com/profile.php?id=61560900343761
    icon: fab fa-facebook

