remote_theme: mmistakes/so-simple-theme
plugins:
- jekyll-remote-theme
- jekyll-paginate

title: Life is better by bike
description: ... here are the receipts
logo: "images/img/bike-logo-01.png"

google_analytics:
include:
  - _pages
  - _myth-busting
exclude:
  - docker-compose.yml
  - Gemfile

collections:
  myth-busting:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true
  - scope:
      path: _myth-busting
      type: myth-busting
    values:
      layout: post
      share: true

paginate: 15
paginate_path: /page:num/

author:
  name: BikeSOMa_NJ
  picture:
  email:
  links:
    - title: Instagram
      url: https://instagram.com/bikesoma_nj
      icon: fab fa-instagram
    - title: Facebook
      url: https://www.facebook.com/profile.php?id=61560900343761
      icon: fab fa-facebook

footer_links:
  - title: Instagram
    url: https://instagram.com/bikesoma_nj
    icon: fab fa-instagram
  - title: Facebook
    url: https://www.facebook.com/profile.php?id=61560900343761
    icon: fab fa-facebook
  - title: Github
    url: https://github.com/robhowley/betterby-bike
    icon: fab fa-github
