remote_theme: mmistakes/so-simple-theme
plugins:
- jekyll-remote-theme

title: Life is better by bike
description: ... and here are the receipts
logo: "images/img/bike-logo-01.png"

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true

google_analytics:
exclude:
  - docker-compose.yml
  - Gemfile

author:
  name: BikeSOMa_NJ
  picture:
  email:
  links:
    - title: Instagram
      url: https://instagram.com/bikesoma_nj
      icon: fab fa-instagram

footer_links:
  - title: Instagram
    url: https://instagram.com/bikesoma_nj
    icon: fab fa-instagram

