#!/usr/bin/env node
// build.js — generates data.js from markdown source files
// Run: node build.js

const fs   = require('fs');
const path = require('path');
const ROOT = __dirname;

// ─── Frontmatter parser ───────────────────────────────────────────────────────
function parseFM(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { fm: {}, content: raw.trim() };
  const fm = {};
  let key = null;
  for (const line of m[1].split('\n')) {
    const l    = line.replace(/\r$/, '');
    const item = l.match(/^[ \t]+-[ \t]+(.+)$/);
    const kv   = l.match(/^([\w-]+):[ \t]*(.*)$/);
    if (item && key) {
      if (!Array.isArray(fm[key])) fm[key] = [];
      fm[key].push(item[1].trim().replace(/^["']|["']$/g, ''));
    } else if (kv) {
      key = kv[1];
      const v = kv[2].trim().replace(/^["']|["']$/g, '');
      fm[key] = v === '' ? [] : v;
    }
  }
  return { fm, content: m[2].trim() };
}

// ─── Excerpt extractor ────────────────────────────────────────────────────────
function excerpt(md, max = 195) {
  for (const para of md.split(/\n\n+/)) {
    const c = para
      .replace(/^#+\s+/gm, '')
      .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .replace(/[*_`~>|]/g, '')
      .replace(/\s+/g, ' ')
      .trim();
    if (c.length > 30) return c.slice(0, max) + (c.length > max ? '…' : '');
  }
  return '';
}

// ─── Load posts from a directory ─────────────────────────────────────────────
function loadDir(rel) {
  const dir = path.join(ROOT, rel);
  if (!fs.existsSync(dir)) return [];
  const slug = rel.replace(/.*\//, '');
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => {
      const { fm, content } = parseFM(fs.readFileSync(path.join(dir, f), 'utf8'));
      const dm = f.match(/^(\d{4}-\d{2}-\d{2})/);
      const cats = Array.isArray(fm.categories) ? fm.categories
        : fm.categories ? [fm.categories] : [];
      const tags = Array.isArray(fm.tags) ? fm.tags
        : fm.tags ? [fm.tags] : [];
      return {
        id: slug + '-' + f.replace('.md', ''),
        title: fm.title || '',
        date: dm ? dm[1] : '',
        categories: cats,
        tags,
        content,
        excerpt: excerpt(content),
      };
    });
}

// ─── Load myth-busting collection ────────────────────────────────────────────
function loadMyths() {
  const dir = path.join(ROOT, '_myth-busting');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => {
      const { fm, content } = parseFM(fs.readFileSync(path.join(dir, f), 'utf8'));
      return { id: 'myth-' + f.replace('.md', ''), title: fm.title || '', content };
    });
}

const posts = [
  ...loadDir('_posts/safety'),
  ...loadDir('_posts/biz'),
  ...loadDir('_posts/environment'),
  ...loadDir('_posts/news'),
].sort((a, b) => b.date.localeCompare(a.date));

const myths = loadMyths();

// ─── Output data.js ───────────────────────────────────────────────────────────
const dataJs = `// data.js — generated by build.js, do not edit manually
export const POSTS = ${JSON.stringify(posts, null, 2)};
export const MYTHS = ${JSON.stringify(myths, null, 2)};
`;

fs.writeFileSync(path.join(ROOT, 'js', 'data.js'), dataJs, 'utf8');
console.log(`✓ Built js/data.js — ${posts.length} posts, ${myths.length} myths`);
