name: CI
on:
  push:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - run: ls -a

      - name: run markdown lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.yaml'
          args: '**/*.md'
