name: CI
on:
  push:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: run markdown lin
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.yaml
          files: .
          version: 0.41.0
