name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: articulate/actions-markdownlint@v1
        with:
          config:
          files: .markdownlint.yaml
          version: 0.41.0
