name: CI
on:
  push:
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: run markdown lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.yaml'
          args: '**/*.md'
          ignore: './betterby-bike/CHANGELOG.md'
